framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

            failed: '%env(MESSENGER_FAILD_TRANSPORT_DSN)%'

        routing:
            'App\Infrastructure\Queue\Message\ServiceMethodMessage': async
