framework:
    messenger:
        transports:
            async: 
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              retry_strategy: 
                max_retries: 0

            failed: '%env(MESSENGER_FAILD_TRANSPORT_DSN)%'

        routing:
            '\App\Infrastructure\Queue\Message\ServiceMethodMessage': async
