security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            remember_me:
              secret:   '%kernel.secret%'
              lifetime: 604800 # 1 week in seconds
              path:     /

            anonymous: true
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            guard:
                authenticators:
                    - App\Security\AppAuthenticator
            logout:
                path: user_logout
             
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

        - { path: ^/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sitemap, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/, roles: ROLE_USER }