version: '3.8'

networks: 
    dev:

services: 
    #Mailhog
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog-container
        restart: always
        ports:
            - 8025:8025 # web ui
            - 1025:1025 # smtp server
        networks:
            - dev
#Supposing you've an Apache or Nginx Docker container named web_service_container listening on port 80:
#$ docker run --rm -it --link web_service_container wernight/ngrok ngrok http web_service_container:80